# Spawn location for /spawn command

spawn:
  world: "spawn" # Spawn world
  x: 0.5 # X Coordinate of spawn
  y: 101 # Y Coordinate of spawn
  z: 0.5 # Z Coordinate of spawn
  yaw: 180 # Rotation of player
  pitch: -5 # Face axis of player
  limit: 75 #Height limit

# Commands config

commands:
  cooldown:
    timer: 5

# Whitelisted blocks for spawn

block-blacklist:
  enabled: true
  list: ["spruce trapdoor", "spruce door", "spruce button", "spruce fence_gate", "item frame", "painting", "chest", "barrel"]

# Blacklisted mobs

mob-blacklist:
  enabled: false
  list: ["bat", "squid", "dolphin", "tropical fish", "cod", "salmon", "pufferfish", "turtle"]

# Kits config

kits:
  nowicjusz:
    cooldown: 86400
    items:
      '0':
        id: "example_sword" # Oraxen ID
        amount: 1 # Amount
      '1':
        id: "grape"
        amount: 2