# Spawn location for /spawn command

spawn:
  world: "world" # Spawn world
  x: 0.5 # X Coordinate of spawn
  y: 101 # Y Coordinate of spawn
  z: 0.5 # Z Coordinate of spawn
  yaw: 180 # Rotation of player
  pitch: -5 # Face axis of player
  limit: 75 #Height limit

# Commands config

commands:
  cooldown:
    timer: 5

# Whitelisted blocks for spawn

whitelist: ["spruce_trapdoor", "spruce_door", "spruce_button", "spruce_fence_gate", "item_frame", "painting"]

# Kits config

kits:
  nowicjusz:
    cooldown: 86400
    items:
      '0':
        id: "example_sword" # Oraxen ID
        amount: 1 # Amount
      '1':
        id: "grape"
        amount: 2