name: bpSurvival
version: '0.1'
authors: [botprzemek]
website: 'https://www.github.com/botprzemek/bpSurvival/'
description: Survival addons (1.18.2)
main: pl.botprzemek.bpSurvival.BpSurvival
api-version: '1.18'
softdepend: [PlaceholderAPI, Oraxen]
commands:
  bpsurvival:
    aliases: [bps]
    default: op
    description: Reload command
  settings:
    aliases: [set]
    default: op
    description: Settings command
  spawn:
    aliases: [s]
    default: op
    description: Spawn command
  vanish:
    aliases: [ukryj, v]
    default: op
    description: Vanish command
  tprequest:
    aliases: [tpa, tpwyslij]
    default: op
    description: Teleport request command
  tpaccept:
    aliases: [tpakceptuj]
    default: op
    description: Teleport accept command
  tpdeny:
    aliases: [tpodrzuc]
    default: op
    description: Teleport deny command
  home:
    aliases: [dom, h]
    default: op
    description: Home command
  sethome:
    aliases: [ustawdom]
    default: op
    description: Set home command
  kit:
    aliases: [zestaw]
    default: op
    description: Kit command
  streaming:
    aliases: [czat]
    default: op
    description: Disables chat command
  message:
    aliases: [msg, wiadomosc]
    default: op
    description: Message command
  reply:
    aliases: [r, odpowiedz]
    default: op
    description: Reply command
permissions:
  bpsurvival.*:
    description: Gives access to all bpSurvival commands
    children:
      bpsurvival.chat: true
      bpsurvival.reload: true
      bpsurvival.settings: true
      bpsurvival.spawn: true
      bpsurvival.vanish: true
      bpsurvival.tprequest: true
      bpsurvival.tpaccept: true
      bpsurvival.tpdeny: true
      bpsurvival.home: true
      bpsurvival.sethome: true
      bpsurvival.kit: true
      bpsurvival.streaming: true
      bpsurvival.message: true
      bpsurvival.reply: true